# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9b3f90d9a7d3b1d100a8ba499af78eda537caf715251d14d4faa9fbf67db001967a349bb49b25ee322dcb9360f0bc3919d4d115d18f1514e932c72938c89a985

test:
  secret_key_base: 416ed6249ddc2664e65315de9c21dfa0ed463803b9d04ea927d8e3f085d27833ef310f779ef5a1809cdc71e351ec503235e591274c66b0142317d805fd5a4b4a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
